/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.seata.rm.datasource.undo.postgresql;

import org.apache.seata.common.loader.LoadLevel;
import org.apache.seata.core.compressor.CompressorType;
import org.apache.seata.core.constants.ClientTableColumnsName;
import org.apache.seata.rm.datasource.undo.AbstractUndoLogManager;
import org.apache.seata.rm.datasource.undo.UndoLogParser;
import org.apache.seata.sqlparser.util.JdbcConstants;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

@LoadLevel(name = JdbcConstants.POSTGRESQL)
public class PostgresqlUndoLogManager extends AbstractUndoLogManager {

    private static final Logger LOGGER = LoggerFactory.getLogger(PostgresqlUndoLogManager.class);

    /*
     * Do not hardcode the sequence name in SQL anymore.
     * The table's id column should be generated by the database (SERIAL/BIGSERIAL/IDENTITY or DEFAULT nextval(...)).
     * Use PostgreSQL's RETURNING clause to obtain the generated primary key.
     */
    private static final String INSERT_UNDO_LOG_SQL = "INSERT INTO " + UNDO_LOG_TABLE_NAME + " (
            + ClientTableColumnsName.UNDO_LOG_BRANCH_XID + ", 
            + ClientTableColumnsName.UNDO_LOG_XID + ", 
            + ClientTableColumnsName.UNDO_LOG_CONTEXT + ", 
            + ClientTableColumnsName.UNDO_LOG_ROLLBACK_INFO + ", 
            + ClientTableColumnsName.UNDO_LOG_LOG_STATUS + ", 
            + ClientTableColumnsName.UNDO_LOG_LOG_CREATED + ", 
            + ClientTableColumnsName.UNDO_LOG_LOG_MODIFIED + ") 
            + "VALUES (?, ?, ?, ?, ?, now(), now()) RETURNING " + ClientTableColumnsName.UNDO_LOG_ID;

    private static final String DELETE_UNDO_LOG_BY_CREATE_SQL = "DELETE FROM " + UNDO_LOG_TABLE_NAME + " WHERE 
            + ClientTableColumnsName.UNDO_LOG_ID + " IN (" 
            + "SELECT " + ClientTableColumnsName.UNDO_LOG_ID + " FROM " + UNDO_LOG_TABLE_NAME
            + " WHERE " + ClientTableColumnsName.UNDO_LOG_LOG_CREATED + " <= ? LIMIT ?" + ")";

    @Override
    public int deleteUndoLogByLogCreated(Date logCreated, int limitRows, Connection conn) throws SQLException {
        PreparedStatement deletePST = null;
        try {
            deletePST = conn.prepareStatement(DELETE_UNDO_LOG_BY_CREATE_SQL);
            deletePST.setDate(1, new java.sql.Date(logCreated.getTime()));
            deletePST.setInt(2, limitRows);
            int deleteRows = deletePST.executeUpdate();
            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug("batch delete undo log size {}", deleteRows);
            }
            return deleteRows;
        } catch (Exception e) {
            if (!(e instanceof SQLException)) {
                e = new SQLException(e);
            }
            throw (SQLException) e;
        } finally {
            if (deletePST != null) {
                deletePST.close();
            }
        }
    }

    @Override
    protected void insertUndoLogWithNormal(
            String xid, long branchID, String rollbackCtx, byte[] undoLogContent, Connection conn) throws SQLException {
        insertUndoLog(xid, branchID, rollbackCtx, undoLogContent, State.Normal, conn);
    }

    @Override
    protected void insertUndoLogWithGlobalFinished(String xid, long branchId, UndoLogParser parser, Connection conn)
            throws SQLException {
        insertUndoLog(
                xid,
                branchId,
                buildContext(parser.getName(), CompressorType.NONE),
                parser.getDefaultContent(),
                State.GlobalFinished,
                conn);
    }

    private void insertUndoLog(
            String xid, long branchID, String rollbackCtx, byte[] undoLogContent, State state, Connection conn)
            throws SQLException {
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            pst = conn.prepareStatement(INSERT_UNDO_LOG_SQL);
            int idx = 1;
            pst.setLong(idx++, branchID);
            pst.setString(idx++, xid);
            pst.setString(idx++, rollbackCtx);
            pst.setBytes(idx++, undoLogContent);
            pst.setInt(idx++, state.getValue());

            // Use RETURNING to get the generated id (PostgreSQL-specific behavior; the JDBC driver returns a ResultSet)
            rs = pst.executeQuery();
            if (rs != null && rs.next()) {
                long generatedId = rs.getLong(1);
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("insert undo_log generated id: {}", generatedId);
                }
                // The current method signature does not allow setting the id on an UndoLogDO instance,
                // so we only log the generated id. If needed, consider returning the id or passing in the UndoLogDO.
            } else {
                throw new SQLException("Insert undo_log failed, no id returned by RETURNING.");
            }
        } catch (Exception e) {
            if (!(e instanceof SQLException)) {
                e = new SQLException(e);
            }
            throw (SQLException) e;
        } finally {
            if (rs != null) {
                rs.close();
            }
            if (pst != null) {
                pst.close();
            }
        }
    }
}